### ISSUE TITLE
Support custom OAuth servers in config

### ISSUE THREAD

**Issue by aaronpk** [bnfinet/lasso#1]
I'd love to be able to change the OAuth server that this uses to a custom server. Given that it's using the generic OAuth client, it looks like you'd just need to add a few settings to the `config.yml` file. 

The OAuth client [[1]](https://github.com/bnfinet/lasso/blob/master/handlers/handlers.go#L54) seems to take the following config values: `ClientID`, `ClientSecret`, `Scopes` and `Endpoint` which contains both the authorization and token endpoints. [[2]](https://github.com/golang/oauth2/blob/master/google/google.go#L31) Moving these to the config file should make it super easy to use with any OAuth 2 server!

**Comment by bnfinet** [comment]
implemented at https://github.com/bnfinet/lasso/commit/57e83cfdd5bf7c8f7c0c09a4098aab1f76dfafc1
